/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nghia_dien.views;

import com.nghia_dien.controllers.Client;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.Callback;
import com.teamdev.jxbrowser.chromium.JSObject;
import com.teamdev.jxbrowser.chromium.events.ScriptContextAdapter;
import com.teamdev.jxbrowser.chromium.events.ScriptContextEvent;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.*;

/**
 *
 * @author Nghia Cao
 */
public class MainFrameClient extends javax.swing.JFrame {

    private Client client = new Client();
    private Browser browser;

    /**
     * Creates new form MainFrameClient
     */
    public MainFrameClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConnect = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnConnect = new javax.swing.JButton();
        txtHost = new javax.swing.JTextField();
        txtPort = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        btnDisconnect = new javax.swing.JButton();
        btnConnectStatus = new javax.swing.JButton();
        pnlTag = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLatitude = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLongtitude = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPlaceName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnTag = new javax.swing.JButton();
        btnPlaceList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPlaces = new javax.swing.JList<>();
        btnListFriends = new javax.swing.JButton();
        btnClearMarkers = new javax.swing.JButton();
        pnlMap = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Places Manager");

        pnlConnect.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Connect", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        pnlConnect.setMaximumSize(new java.awt.Dimension(963, 47));

        jLabel3.setText("Address:");

        jLabel4.setText("Port:");

        jLabel5.setText("Username:");

        jLabel6.setText("Password:");

        btnConnect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        txtHost.setText("192.168.0.106");
        txtHost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHostKeyPressed(evt);
            }
        });

        txtPort.setText("5500");
        txtPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortActionPerformed(evt);
            }
        });

        txtUsername.setText("tungbt");

        password.setText("abc123");

        btnDisconnect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDisconnect.setForeground(new java.awt.Color(204, 0, 0));
        btnDisconnect.setText("Disconnected");
        btnDisconnect.setEnabled(false);
        btnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisconnectActionPerformed(evt);
            }
        });

        btnConnectStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nghia_dien/resources/fail.png"))); // NOI18N

        javax.swing.GroupLayout pnlConnectLayout = new javax.swing.GroupLayout(pnlConnect);
        pnlConnect.setLayout(pnlConnectLayout);
        pnlConnectLayout.setHorizontalGroup(
            pnlConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConnectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHost, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConnect)
                .addGap(18, 18, 18)
                .addComponent(btnDisconnect)
                .addGap(18, 18, 18)
                .addComponent(btnConnectStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlConnectLayout.setVerticalGroup(
            pnlConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConnectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(btnConnect)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisconnect)
                    .addComponent(btnConnectStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTag.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel1.setText("Latitude:");

        txtLatitude.setEditable(false);
        txtLatitude.setText("180");
        txtLatitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLatitudeActionPerformed(evt);
            }
        });

        jLabel2.setText("Longtitude:");

        txtLongtitude.setEditable(false);
        txtLongtitude.setText("180");

        jLabel7.setText("Place:");

        txtPlaceName.setEditable(false);
        txtPlaceName.setText("Hanoi");

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnTag.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnTag.setText("Tag");
        btnTag.setEnabled(false);
        btnTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTagActionPerformed(evt);
            }
        });

        btnPlaceList.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPlaceList.setText("Places List");
        btnPlaceList.setEnabled(false);
        btnPlaceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceListActionPerformed(evt);
            }
        });

        listPlaces.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listPlaces);

        btnListFriends.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnListFriends.setText("Friends List");
        btnListFriends.setEnabled(false);
        btnListFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListFriendsActionPerformed(evt);
            }
        });

        btnClearMarkers.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnClearMarkers.setText("Clear Markers");
        btnClearMarkers.setEnabled(false);
        btnClearMarkers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearMarkersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTagLayout = new javax.swing.GroupLayout(pnlTag);
        pnlTag.setLayout(pnlTagLayout);
        pnlTagLayout.setHorizontalGroup(
            pnlTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTagLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTagLayout.createSequentialGroup()
                        .addGroup(pnlTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTagLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnPlaceList)
                                .addGap(29, 29, 29)
                                .addComponent(btnListFriends))
                            .addGroup(pnlTagLayout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(32, 32, 32)
                                .addComponent(btnTag)
                                .addGap(31, 31, 31)
                                .addComponent(btnClearMarkers)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlTagLayout.createSequentialGroup()
                        .addGroup(pnlTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlTagLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLongtitude, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTagLayout.createSequentialGroup()
                                .addGroup(pnlTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPlaceName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLatitude, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTagLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        pnlTagLayout.setVerticalGroup(
            pnlTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTagLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(pnlTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlaceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(pnlTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLongtitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnTag)
                    .addComponent(btnClearMarkers))
                .addGap(18, 18, 18)
                .addGroup(pnlTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListFriends)
                    .addComponent(btnPlaceList))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pnlMap.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Map", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        pnlMap.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlConnect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        String serverIP = txtHost.getText().trim();
        int serverPort;
        try {
            serverPort = Integer.parseInt(txtPort.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please check server ip or server port again!");
            return;
        }

        try {
            this.client = new Client(serverIP, serverPort);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Connect failed!");
            return;
        }

        String username = txtUsername.getText().trim();
        String password = new String(this.password.getPassword());
        try {
            if (client.login(username, password)) {
                showMap();
                btnConnect.setEnabled(false);
                btnDisconnect.setEnabled(true);
                btnConnectStatus.setIcon(new ImageIcon("src/com/nghia_dien/resources/OK.png"));
                pnlMap.setVisible(true);
                btnSave.setEnabled(true);
                btnListFriends.setEnabled(true);
                btnPlaceList.setEnabled(true);
                btnClearMarkers.setEnabled(true);
                btnTag.setEnabled(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(MainFrameClient.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }


    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconnectActionPerformed
        this.client.disconnect();

        btnConnect.setEnabled(true);
        btnDisconnect.setEnabled(false);
        btnConnectStatus.setIcon(new ImageIcon("src/com/nghia_dien/resources/fail.png"));
        pnlMap.setVisible(false);
        btnSave.setEnabled(false);
        btnListFriends.setEnabled(false);
        btnPlaceList.setEnabled(false);
        btnClearMarkers.setEnabled(false);
        btnTag.setEnabled(false);
    }//GEN-LAST:event_btnDisconnectActionPerformed

    private void txtPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortActionPerformed

    private void txtLatitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLatitudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLatitudeActionPerformed

    private void btnTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTagActionPerformed
        String placeName;
        float latitude;
        float longtitude;
        try {
            placeName = txtPlaceName.getText();
            latitude = Float.parseFloat(txtLatitude.getText());
            longtitude = Float.parseFloat(txtLongtitude.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(this, "Please mark a place before tagging friend!");
            return;
        }
        String username = JOptionPane.showInputDialog(this, "Enter username");
        if (username.length() <= 0) {
            return;
        }
        //   client.addFriend(username);
        try {
            if (this.client.tagFriend(username, placeName, latitude, longtitude) == false) {
                JOptionPane.showMessageDialog(this, "Can't tag your friend in this place.");
            } else {
                JOptionPane.showMessageDialog(this, "Successfully!");
            }

        } catch (IOException ex) {
            Logger.getLogger(MainFrameClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTagActionPerformed

    private void btnClearMarkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearMarkersActionPerformed
        browser.executeJavaScript("deleteAllMarkers()");
        txtPlaceName.setText("");
        txtLatitude.setText("");
        txtLongtitude.setText("");
    }//GEN-LAST:event_btnClearMarkersActionPerformed

    private void btnPlaceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceListActionPerformed
        try {
            String[] places = this.client.listPlaces();
            DefaultListModel listModel = new DefaultListModel();
            for (String place : places) {
                String[] info = place.split("\\|");
                String item = info[0] + "(lat:" + info[1] + ", lng:" + info[2] + ")";
                listModel.addElement(item);
            }
            listPlaces.setModel(listModel);
        } catch (IOException ex) {
            Logger.getLogger(MainFrameClient.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPlaceListActionPerformed

    private void btnListFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListFriendsActionPerformed
        try {
            String[] friends = this.client.listFriends();
            DefaultListModel listModel = new DefaultListModel();
            for (String friend : friends) {
                listModel.addElement(friend);
            }
            listPlaces.setModel(listModel);
        } catch (IOException ex) {
            Logger.getLogger(MainFrameClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListFriendsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            String address = txtPlaceName.getText();
            float lat = Float.parseFloat(txtLatitude.getText());
            float lng = Float.parseFloat(txtLongtitude.getText());

            if (this.client.addPlace(address, lat, lng)) {
                JOptionPane.showMessageDialog(this, "Successfully!");
            }
        } catch (IOException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "You haven't mark a place in map!");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtHostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHostKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnConnect.doClick();
        }
    }//GEN-LAST:event_txtHostKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearMarkers;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnConnectStatus;
    private javax.swing.JButton btnDisconnect;
    private javax.swing.JButton btnListFriends;
    private javax.swing.JButton btnPlaceList;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listPlaces;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel pnlConnect;
    private javax.swing.JPanel pnlMap;
    private javax.swing.JPanel pnlTag;
    private javax.swing.JTextField txtHost;
    private static javax.swing.JTextField txtLatitude;
    private static javax.swing.JTextField txtLongtitude;
    private static javax.swing.JTextField txtPlaceName;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    public void showMap() {
        browser = new Browser();
        browser.addScriptContextListener(new ScriptContextAdapter() {
            @Override
            public void onScriptContextCreated(ScriptContextEvent event) {
                browser.executeJavaScriptAndReturnValue("window").asObject().setProperty("java", new JavaCallback());
            }
        });

        BrowserView view = new BrowserView(browser);
        pnlMap.add(view, BorderLayout.CENTER);
        this.add(pnlMap, BorderLayout.CENTER);
        this.setVisible(true);
        Browser.invokeAndWaitFinishLoadingMainFrame(browser, new Callback<Browser>() {
            @Override
            public void invoke(Browser t) {
                browser.loadURL("C:\\Users\\HP Zbook 15\\Desktop\\Places Manager\\src\\com\\nghia_dien\\resources\\map.html");

            }
        });
//       browser.executeJavaScriptAndReturnValue(
//                "map.addListener('click', function(e) {\n" +
//                        "placeMarker(e.latLng, map);\n" +
//                        "});\n" +
//                        "\n" +
//                        "function placeMarker(position, map) {\n" +
//                        "        var marker = new google.maps.Marker({\n" +
//                        "        position: position,\n" +
//                        "        map: map,\n" +
//                        "        title:'test point',\n " +
//                        "    });\n" +
//                        "    map.panTo(position);\n" +
//                        "    window.java.onMarkerAdded(position);" +
//                        "}");
    }

    public static class JavaCallback {

        public void onMarkerAdded(JSObject position) {
            double lat = position.getProperty("lat").getNumberValue();
            double lng = position.getProperty("lng").getNumberValue();
            String placeName = position.getProperty("address").getStringValue();

            txtLongtitude.setText(String.valueOf(lng));
            txtLatitude.setText(String.valueOf(lat));
            txtPlaceName.setText(placeName);
        }
    }

}
